add negate function to Q object
pivotbio/bulk-api-python-client pull request #155
Opened 2021-01-11 21:42 UTC by donnell794

mimic django ~Q for not Q calls

2021-01-12 19:48 UTC, glassresistor requested changes

2021-01-12 19:48 UTC, glassresistor commented on bulk_api_client/query_helpers.py
> +    def __invert__(self):
I'm assuming this works but have no idea whats going on here.  Maybe add some docstrings to the _ methods or inline comments to explain whats going on here.

2021-01-12 19:57 UTC, aawiegel commented
This is a random thought and out of scope for this PR. But, if this code is just the django Q object code with extra code for outputting the logical operators in the format the API client understands, why not inherit the Q object from Django and extend it to include that code instead of duplicating it?

2021-01-19 20:02 UTC, glassresistor approved these changes

2021-01-19 20:03 UTC, merged