Create ModelObjs without swagger definitions.
pivotbio/bulk-api-python-client pull request #158
Opened 2021-01-22 18:15 UTC by georgedorn

Implements creating ModelObjs from autogenerated schema endpoint instead of swagger.

2021-03-03 18:43 UTC, glassresistor requested changes
Great work

2021-03-03 18:43 UTC, glassresistor commented on bulk_api_client/model.py
>              if "api_download" in field_val:
This isn't going to work but for good reasons.  the type should actually be uri now

2021-03-03 18:43 UTC, glassresistor commented on bulk_api_client/model.py
> +            if field == "_meta":
I was about to suggest making this slightly more concise by removing it before the list but i like that it visually large

2021-03-03 18:43 UTC, glassresistor commented on bulk_api_client/model.py
>              if "api_download" in field_val:
the issue was filetype and fk was overloaded. so you should check this in the field

2021-03-03 19:05 UTC, georgedorn commented on bulk_api_client/model.py
>              if "api_download" in field_val:
Oh, right.  I think maybe I need to also write a test for api_download.

2021-03-04 01:53 UTC, georgedorn commented on bulk_api_client/model.py
>              if "api_download" in field_val:
That test revealed there wasn't really a safe way (imo) to deal with files without fixing the reported schema on data_warehouse.  Added a PR for that to the description.

2021-03-04 20:44 UTC, glassresistor approved these changes

2021-03-04 20:44 UTC, merged