Feature/add stored query method
pivotbio/bulk-api-python-client pull request #182
Opened 2021-11-16 23:29 UTC by LuapRebel

- Add `call_stored_query` method to `Client` to allow users to call an existing Stored Query and update parameters.
- Add tests

2021-11-16 23:41 UTC, aawiegel requested changes
Looks good I think there's some hidden gotchas the users of this method might run into as is though.

2021-11-16 23:41 UTC, aawiegel commented on bulk_api_client/client.py
> +                return yaml_field
Why are you nesting a function within this instance method? Seems like a really weird choice. If this is a static method you don't want to expose to users I would make it a private function in the module (e.g., `_get_yaml_field`)

2021-11-16 23:41 UTC, aawiegel commented on bulk_api_client/client.py
> +            stored_query = StoredQuery.query(filter={"name": name})
I would use either `.get` or `.list` with a filter so you can access the data directly without having to use a dataframe because that is a really unnecessary data structure for trying to get the query back (I don't think anyone would ever want more than one?) Getting back a JSON/dict would be much easier to work with

2021-11-16 23:41 UTC, aawiegel commented on bulk_api_client/client.py
> +            }
I'm not sure it is a really good idea to have these set by default to certain values without the user knowing, like if I do not set `distinct` I don't think I would expect it to be `True`. I would potentially separate out the logic of calling a specific stored query _exactly_ with another method to override the query because right now this method does two things.

2021-11-16 23:55 UTC, LuapRebel commented on bulk_api_client/client.py
> +                return yaml_field
Because I don't know better. I put it there because I didn't think it would be used outside this function.

I think I'll redo this function to not use the Stored Query either.  When I implement the change below to use `.get`, I'll have to rewrite a bunch of this.
I also just realized that this functionality may be present elsewhere in the repo, so I'll check for that too.

Should I add this similarly to how the `is_json` function is on line 20?

2021-11-16 23:55 UTC, LuapRebel commented on bulk_api_client/client.py
> +            stored_query = StoredQuery.query(filter={"name": name})
Good idea. Not sure why I didn't do that in the first place.

2021-11-16 23:55 UTC, LuapRebel commented on bulk_api_client/client.py
> +            }
Makes sense. I will separate it out. 
My default is generally to remove duplicate rows, so I made the assumption that was a good default.

2021-11-17 23:26 UTC, aawiegel commented on bulk_api_client/client.py
> +                return yaml_field
Yeah, that would be a good example of a pattern to follow.

2021-11-18 16:45 UTC, LuapRebel commented on bulk_api_client/client.py
> +                return yaml_field
I ended up removing this as I realized it wasn't actually even necessary. Yaml is dealt with automatically via the query method.

2021-11-18 16:46 UTC, LuapRebel commented on bulk_api_client/client.py
> +            }
I just removed this entirely so it's on the user or the existing query to define them.

2021-11-18 18:58 UTC, aawiegel requested changes
Mocking out `call_stored_query` actually avoids testing it entirely, you would want to mock that method out when you were writing some other method instead. I think what you want to mock here is `StoredQuery` and `ContentType` but I'd have to think about the right way to go about that.

2021-11-19 22:13 UTC, aawiegel reviewed
Looks good other than one test that maybe isn't necessary

2021-11-19 22:13 UTC, aawiegel commented on tests/integration_tests.py
> +        assert mock_call_stored_query.call_count == 1
Is this test really testing anything? If some other method called the method `call_stored_query` this test would be useful,  but for now I'm not sure this is really worthwhile

2021-11-19 22:20 UTC, LuapRebel commented on tests/integration_tests.py
> +        assert mock_call_stored_query.call_count == 1
I meant to remove this but I guess I didn't. Let me remove it and re-push.

2021-11-19 22:27 UTC, aawiegel approved these changes
:shipit:

2021-11-19 22:27 UTC, merged